export type JobT = {
    _id: string,
    title: string,
    company: string,
    location: string,
    salary: string,
    salary_min: string,
    salary_max: string,
    url: string,
    post_date: Date,
    description: string,
    source: string,
    aiScore: number,
    isRelevant: boolean,
    aiReason: string,
    aiRated: string,
    createdAt: Date,
}
